### ISSUE TITLE
Setup Application Cannot Be Started: Activation Failed.

### ISSUE THREAD

**Issue by madingess** [ELREVENGE/HaloSaveTransferTool#1]
Running the Setup application as administrator, I encounter the error: 
"Cannot Start Application. Application cannot be started. Contact the application vendor."

A "Details..." option provides details of the error and stack trace. See file below.

[QRDK9SM0.log](https://github.com/ELREVENGE/HaloSaveTransferTool/files/4014436/QRDK9SM0.log)

I tried working out the error myself, following the instructions bolded in the response here (https://social.msdn.microsoft.com/Forums/vstudio/en-US/6229334e-d5ef-4016-9e7e-1c8718be8d43/access-is-denied-exception-from-hresult-0x80070005-eaccessdenied-in-vbnet).

But to no avail. 

I understand the tool is new and documentation is underway. Thought this may help.

Also, Avast doesn't like the application ;)

**Comment by madingess** [comment]
Strike that. After much deliberation, Avast has decided it has no problem with your installer.

**Comment by ELREVENGE** [comment]
So is this issue resolved or is the installer still being an issue? I see from the .log that it was denied access I would assume Avast was the cause but wanted to make sure you got it working alright.

**Comment by madingess** [comment]
No the dislike of Avast is unrelated. The issue is yet unresolved. The microsoft link above gives something of a description of the error.

**Comment by ELREVENGE** [comment]
Try extracting and running this I believe this is an installer issue so I have grabbed the files from the release folder after building. They should work but the program will not show up in window's installed programs list. 
[HaloSaveTransferTool_v1.0.2.1.zip](https://github.com/ELREVENGE/HaloSaveTransferTool/files/4014945/HaloSaveTransferTool_v1.0.2.1.zip)

**Comment by madingess** [comment]
Works like a charm. Thanks mate.
